use database financial_analytics_wh;
use schema staging;
CREATE TABLE income_statement (
    Id INT , -- Equivalent to IDENTITY
    date STRING, -- Equivalent to NVARCHAR
    tax_effect_of_unusual_items FLOAT,
    tax_rate_for_calcs FLOAT,
    normalized_ebitda FLOAT,
    total_unusual_items FLOAT,
    total_unusual_items_excluding_goodwill FLOAT,
    net_income_from_continuing_operation_net_minority_interest FLOAT,
    reconciled_depreciation FLOAT,
    reconciled_cost_of_revenue FLOAT,
    ebitda FLOAT,
    ebit FLOAT,
    net_interest_income FLOAT,
    interest_expense FLOAT,
    interest_income FLOAT,
    normalized_income FLOAT,
    net_income_from_continuing_and_discontinued_operation FLOAT,
    total_expenses FLOAT,
    rent_expense_supplemental FLOAT,
    diluted_average_shares FLOAT,
    basic_average_shares FLOAT,
    diluted_eps FLOAT,
    basic_eps FLOAT,
    diluted_ni_availto_com_stockholders FLOAT,
    net_income_common_stockholders FLOAT,
    otherunder_preferred_stock_dividend FLOAT,
    net_income FLOAT,
    net_income_including_noncontrolling_interests FLOAT,
    net_income_discontinuous_operations FLOAT,
    net_income_continuous_operations FLOAT,
    tax_provision FLOAT,
    pretax_income FLOAT,
    other_non_operating_income_expenses FLOAT,
    special_income_charges FLOAT,
    other_special_charges FLOAT,
    write_off FLOAT,
    net_non_operating_interest_income_expense FLOAT,
    total_other_finance_cost FLOAT,
    interest_expense_non_operating FLOAT,
    interest_income_non_operating FLOAT,
    operating_income FLOAT,
    operating_expense FLOAT,
    other_operating_expenses FLOAT,
    depreciation_and_amortization_in_income_statement FLOAT,
    amortization FLOAT,
    depreciation_income_statement FLOAT,
    selling_general_and_administration FLOAT,
    selling_and_marketing_expense FLOAT,
    general_and_administrative_expense FLOAT,
    rent_and_landing_fees FLOAT,
    gross_profit FLOAT,
    cost_of_revenue FLOAT,
    total_revenue FLOAT,
    operating_revenue FLOAT,
    minority_interests FLOAT,
    research_and_development FLOAT,
    impairment_of_capital_assets FLOAT,
    gain_on_sale_of_security FLOAT,
    insurance_and_claims FLOAT,
    restructuring_and_mergern_acquisition FLOAT,
    net_income_extraordinary FLOAT,
    total_operating_income_as_reported FLOAT,
    other_income_expense FLOAT,
    gain_on_sale_of_ppe FLOAT,
    earnings_from_equity_interest FLOAT,
    average_dilution_earnings FLOAT,
    preferred_stock_dividends FLOAT,
    depreciation_amortization_depletion_income_statement FLOAT,
    amortization_of_intangibles_income_statement FLOAT,
    other_gand_a FLOAT,
    salaries_and_wages FLOAT,
    occupancy_and_equipment FLOAT,
    other_non_interest_expense FLOAT,
    gain_on_sale_of_business FLOAT,
    other_taxes FLOAT,
    net_policyholder_benefits_and_claims FLOAT,
    earnings_from_equity_interest_net_of_tax FLOAT,
    provision_for_doubtful_accounts FLOAT,
    professional_expense_and_contract_services_expense FLOAT,
    security_id STRING, -- Equivalent to VARCHAR
    security_code INT
);


CREATE TABLE balance_sheet (
    Id INT , -- Equivalent to IDENTITY
    date DATE, -- Equivalent to DATE
    treasury_shares_number NUMBER(18, 2),
    ordinary_shares_number NUMBER(18, 2),
    share_issued NUMBER(18, 2),
    total_debt NUMBER(18, 2),
    tangible_book_value NUMBER(18, 2),
    invested_capital NUMBER(18, 2),
    working_capital NUMBER(18, 2),
    net_tangible_assets NUMBER(18, 2),
    capital_lease_obligations NUMBER(18, 2),
    common_stock_equity NUMBER(18, 2),
    total_capitalization NUMBER(18, 2),
    total_equity_gross_minority_interest NUMBER(18, 2),
    stockholders_equity NUMBER(18, 2),
    other_equity_interest NUMBER(18, 2),
    retained_earnings NUMBER(18, 2),
    additional_paid_in_capital NUMBER(18, 2),
    capital_stock NUMBER(18, 2),
    common_stock NUMBER(18, 2),
    total_liabilities_net_minority_interest NUMBER(18, 2),
    total_non_current_liabilities_net_minority_interest NUMBER(18, 2),
    derivative_product_liabilities NUMBER(18, 2),
    long_term_debt_and_capital_lease_obligation NUMBER(18, 2),
    long_term_capital_lease_obligation NUMBER(18, 2),
    long_term_debt NUMBER(18, 2),
    long_term_provisions NUMBER(18, 2),
    current_liabilities NUMBER(18, 2),
    other_current_liabilities NUMBER(18, 2),
    current_deferred_taxes_liabilities NUMBER(18, 2),
    current_debt_and_capital_lease_obligation NUMBER(18, 2),
    current_capital_lease_obligation NUMBER(18, 2),
    pensionand_other_post_retirement_benefit_plans_current NUMBER(18, 2),
    current_provisions NUMBER(18, 2),
    payables NUMBER(18, 2),
    other_payable NUMBER(18, 2),
    dividends_payable NUMBER(18, 2),
    total_tax_payable NUMBER(18, 2),
    accounts_payable NUMBER(18, 2),
    total_assets NUMBER(18, 2),
    total_non_current_assets NUMBER(18, 2),
    other_non_current_assets NUMBER(18, 2),
    non_current_prepaid_assets NUMBER(18, 2),
    non_current_deferred_taxes_assets NUMBER(18, 2),
    financial_assets NUMBER(18, 2),
    other_investments NUMBER(18, 2),
    investmentin_financial_assets NUMBER(18, 2),
    held_to_maturity_securities NUMBER(18, 2),
    available_for_sale_securities NUMBER(18, 2),
    goodwill_and_other_intangible_assets NUMBER(18, 2),
    other_intangible_assets NUMBER(18, 2),
    goodwill NUMBER(18, 2),
    net_ppe NUMBER(18, 2),
    accumulated_depreciation NUMBER(18, 2),
    gross_ppe NUMBER(18, 2),
    construction_in_progress NUMBER(18, 2),
    other_properties NUMBER(18, 2),
    machinery_furniture_equipment NUMBER(18, 2),
    buildings_and_improvements NUMBER(18, 2),
    land_and_improvements NUMBER(18, 2),
    properties NUMBER(18, 2),
    current_assets NUMBER(18, 2),
    other_current_assets NUMBER(18, 2),
    hedging_assets_current NUMBER(18, 2),
    assets_held_for_sale_current NUMBER(18, 2),
    restricted_cash NUMBER(18, 2),
    prepaid_assets NUMBER(18, 2),
    inventory NUMBER(18, 2),
    finished_goods NUMBER(18, 2),
    work_in_process NUMBER(18, 2),
    raw_materials NUMBER(18, 2),
    other_receivables NUMBER(18, 2),
    taxes_receivable NUMBER(18, 2),
    accounts_receivable NUMBER(18, 2),
    allowance_for_doubtful_accounts_receivable NUMBER(18, 2),
    gross_accounts_receivable NUMBER(18, 2),
    cash_cash_equivalents_and_short_term_investments NUMBER(18, 2),
    other_short_term_investments NUMBER(18, 2),
    cash_and_cash_equivalents NUMBER(18, 2),
    cash_equivalents NUMBER(18, 2),
    cash_financial NUMBER(18, 2),
    net_debt NUMBER(18, 2),
    minority_interest NUMBER(18, 2),
    other_non_current_liabilities NUMBER(18, 2),
    non_current_pension_and_other_postretirement_benefit_plans NUMBER(18, 2),
    non_current_deferred_revenue NUMBER(18, 2),
    non_current_deferred_taxes_liabilities NUMBER(18, 2),
    current_debt NUMBER(18, 2),
    other_inventories NUMBER(18, 2),
    financial_assets_designatedas_fair_value_through_profitor_loss_total NUMBER(18, 2),
    trading_securities NUMBER(18, 2),
    long_term_equity_investment NUMBER(18, 2),
    investmentsin_joint_venturesat_cost NUMBER(18, 2),
    investmentsin_associatesat_cost NUMBER(18, 2),
    preferred_securities_outside_stock_equity NUMBER(18, 2),
    tradeand_other_payables_non_current NUMBER(18, 2),
    investments_in_other_ventures_under_equity_method NUMBER(18, 2),
    investment_properties NUMBER(18, 2),
    fixed_assets_revaluation_reserve NUMBER(18, 2),
    preferred_stock NUMBER(18, 2),
    defined_pension_benefit NUMBER(18, 2),
    non_current_accrued_expenses NUMBER(18, 2),
    investments_and_advances NUMBER(18, 2),
    receivables NUMBER(18, 2),
    cash_cash_equivalents_and_federal_funds_sold NUMBER(18, 2),
    treasury_stock NUMBER(18, 2),
    inventories_adjustments_allowances NUMBER(18, 2),
    non_current_deferred_assets NUMBER(18, 2),
    investmentsin_subsidiariesat_cost NUMBER(18, 2),
    current_deferred_assets NUMBER(18, 2),
    preferred_shares_number NUMBER(18, 2),
    gains_losses_not_affecting_retained_earnings NUMBER(18, 2),
    other_equity_adjustments NUMBER(18, 2),
    non_current_deferred_liabilities NUMBER(18, 2),
    current_deferred_liabilities NUMBER(18, 2),
    current_deferred_revenue NUMBER(18, 2),
    other_current_borrowings NUMBER(18, 2),
    line_of_credit NUMBER(18, 2),
    payables_and_accrued_expenses NUMBER(18, 2),
    current_accrued_expenses NUMBER(18, 2),
    non_current_accounts_receivable NUMBER(18, 2),
    current_deferred_taxes_assets NUMBER(18, 2),
    liabilities_heldfor_sale_non_current NUMBER(18, 2),
    current_notes_payable NUMBER(18, 2),
    employee_benefits NUMBER(18, 2),
    income_tax_payable NUMBER(18, 2),
    non_current_note_receivables NUMBER(18, 2),
    accrued_interest_receivable NUMBER(18, 2),
    loans_receivable NUMBER(18, 2),
    preferred_stock_equity NUMBER(18, 2),
    receivables_adjustments_allowances NUMBER(18, 2),
    dueto_related_parties_non_current NUMBER(18, 2),
    dueto_related_parties_current NUMBER(18, 2),
    duefrom_related_parties_non_current NUMBER(18, 2),
    duefrom_related_parties_current NUMBER(18, 2),
    commercial_paper NUMBER(18, 2),
    interest_payable NUMBER(18, 2),
    notes_receivable NUMBER(18, 2),
    security_id STRING, -- Equivalent to VARCHAR
    security_code INT -- Equivalent to INT
);

CREATE or replace TABLE basic_industry (
    basic_ind_code varchar, -- Equivalent to VARCHAR(11)
    ind_code varchar, -- Equivalent to VARCHAR(8)
    basic_industry varchar, -- Equivalent to VARCHAR(MAX) (unbounded STRING in Snowflake)
    basic_industry_definition varchar, -- Equivalent to VARCHAR(MAX) (unbounded STRING in Snowflake)
    basic_industry_search_optimized varchar -- Equivalent to VARCHAR(255)
);

CREATE or replace TABLE cash_flow (
    id INT , -- Equivalent to IDENTITY(1,1)
    date DATE,
    free_cash_flow NUMBER(18, 2),
    repayment_of_debt NUMBER(18, 2),
    capital_expenditure NUMBER(18, 2),
    end_cash_position NUMBER(18, 2),
    other_cash_adjustment_outside_changein_cash STRING(255),
    beginning_cash_position NUMBER(18, 2),
    effect_of_exchange_rate_changes NUMBER(18, 2),
    changes_in_cash NUMBER(18, 2),
    financing_cash_flow NUMBER(18, 2),
    interest_paid_cff STRING(255),
    cash_dividends_paid STRING(255),
    common_stock_dividend_paid STRING(255),
    net_issuance_payments_of_debt NUMBER(18, 2),
    net_long_term_debt_issuance NUMBER(18, 2),
    long_term_debt_payments NUMBER(18, 2),
    investing_cash_flow NUMBER(18, 2),
    net_other_investing_changes NUMBER(18, 2),
    interest_received_cfi NUMBER(18, 2),
    net_investment_purchase_and_sale NUMBER(18, 2),
    sale_of_investment NUMBER(18, 2),
    purchase_of_investment NUMBER(18, 2),
    net_business_purchase_and_sale NUMBER(18, 2),
    sale_of_business NUMBER(18, 2),
    purchase_of_business NUMBER(18, 2),
    net_ppe_purchase_and_sale NUMBER(18, 2),
    sale_of_ppe NUMBER(18, 2),
    purchase_of_ppe NUMBER(18, 2),
    operating_cash_flow NUMBER(18, 2),
    taxes_refund_paid STRING(255),
    change_in_working_capital NUMBER(18, 2),
    change_in_other_current_liabilities NUMBER(18, 2),
    change_in_other_current_assets NUMBER(18, 2),
    change_in_payable NUMBER(18, 2),
    change_in_inventory NUMBER(18, 2),
    change_in_receivables NUMBER(18, 2),
    other_non_cash_items NUMBER(18, 2),
    provisionand_write_offof_assets NUMBER(18, 2),
    depreciation_and_amortization NUMBER(18, 2),
    amortization_cash_flow NUMBER(18, 2),
    depreciation NUMBER(18, 2),
    gain_loss_on_investment_securities NUMBER(18, 2),
    net_foreign_currency_exchange_gain_loss NUMBER(18, 2),
    gain_loss_on_sale_of_ppe NUMBER(18, 2),
    gain_loss_on_sale_of_business NUMBER(18, 2),
    net_income_from_continuing_operations NUMBER(18, 2),
    issuance_of_debt NUMBER(18, 2),
    issuance_of_capital_stock NUMBER(18, 2),
    net_other_financing_charges NUMBER(18, 2),
    net_common_stock_issuance NUMBER(18, 2),
    common_stock_issuance NUMBER(18, 2),
    net_short_term_debt_issuance NUMBER(18, 2),
    short_term_debt_issuance NUMBER(18, 2),
    long_term_debt_issuance NUMBER(18, 2),
    dividends_received_cfi STRING(255),
    stock_based_compensation NUMBER(18, 2),
    pension_and_employee_benefit_expense NUMBER(18, 2),
    capital_expenditure_reported NUMBER(18, 2),
    short_term_debt_payments NUMBER(18, 2),
    net_investment_properties_purchase_and_sale NUMBER(18, 2),
    net_intangibles_purchase_and_sale NUMBER(18, 2),
    purchase_of_intangibles NUMBER(18, 2),
    other_cash_adjustment_inside_changein_cash STRING(255),
    repurchase_of_capital_stock NUMBER(18, 2),
    net_preferred_stock_issuance NUMBER(18, 2),
    preferred_stock_payments NUMBER(18, 2),
    common_stock_payments NUMBER(18, 2),
    sale_of_investment_properties NUMBER(18, 2),
    interest_received_cfo NUMBER(18, 2),
    interest_paid_cfo STRING(255),
    purchase_of_investment_properties NUMBER(18, 2),
    sale_of_intangibles NUMBER(18, 2),
    deferred_tax NUMBER(18, 2),
    dividend_received_cfo STRING(255),
    cash_flow_from_continuing_financing_activities NUMBER(18, 2),
    cash_flow_from_continuing_investing_activities NUMBER(18, 2),
    cash_flow_from_continuing_operating_activities NUMBER(18, 2),
    change_in_other_working_capital NUMBER(18, 2),
    change_in_payables_and_accrued_expense NUMBER(18, 2),
    unrealized_gain_loss_on_investment_securities NUMBER(18, 2),
    asset_impairment_charge NUMBER(18, 2),
    deferred_income_tax NUMBER(18, 2),
    depreciation_amortization_depletion NUMBER(18, 2),
    amortization_of_intangibles NUMBER(18, 2),
    operating_gains_losses NUMBER(18, 2),
    earnings_losses_from_equity_investments NUMBER(18, 2),
    change_in_prepaid_assets STRING(255),
    interest_paid_supplemental_data STRING(255),
    income_tax_paid_supplemental_data STRING(255),
    proceeds_from_stock_option_exercised NUMBER(18, 2),
    change_in_accrued_expense NUMBER(18, 2),
    change_in_account_payable NUMBER(18, 2),
    changes_in_account_receivables NUMBER(18, 2),
    preferred_stock_issuance NUMBER(18, 2),
    dividend_paid_cfo STRING(255),
    preferred_stock_dividend_paid STRING(255),
    cash_flowsfromusedin_operating_activities_direct NUMBER(18, 2),
    interest_paid_direct STRING(255),
    dividends_paid_direct STRING(255),
    classesof_cash_payments NUMBER(18, 2),
    other_cash_paymentsfrom_operating_activities NUMBER(18, 2),
    paymentson_behalfof_employees NUMBER(18, 2),
    paymentsto_suppliersfor_goodsand_services NUMBER(18, 2),
    classesof_cash_receiptsfrom_operating_activities NUMBER(18, 2),
    other_cash_receiptsfrom_operating_activities NUMBER(18, 2),
    receiptsfrom_customers NUMBER(18, 2),
    taxes_refund_paid_direct STRING(255),
    interest_received_direct NUMBER(18, 2),
    amortization_of_securities NUMBER(18, 2),
    security_id STRING(25),
    security_code INT
);

CREATE TABLE securities (
    security_code INT NOT NULL,
    issuer_name VARCHAR,
    security_id VARCHAR NOT NULL,
    security_name VARCHAR,
    status VARCHAR,
    "group" VARCHAR, -- Reserved keywords like "group" are enclosed in double quotes
    face_value VARCHAR,
    isin_no VARCHAR,
    instrument VARCHAR,
    isubgroup_name VARCHAR,
    isubgroup_name_search_optimized VARCHAR
);


CREATE OR REPLACE TABLE stock_price_history (
    Id INT ,  -- Auto-incrementing integer column
    date DATE,              -- DATE column for the date
    open_price FLOAT,       -- FLOAT column for open price
    high_price FLOAT,       -- FLOAT column for high price
    low_price FLOAT,        -- FLOAT column for low price
    close_price FLOAT,      -- FLOAT column for close price
    wap FLOAT,              -- FLOAT column for weighted average price
    no_of_shares INT,       -- INTEGER column for number of shares
    no_of_trades INT,       -- INTEGER column for number of trades
    total_turnover_rs FLOAT, -- FLOAT column for total turnover in Rs
    deliverable_quantity INT, -- INTEGER column for deliverable quantity
    percent_deli_qty_to_traded_qty FLOAT, -- FLOAT column for percentage of deliverable quantity to traded quantity
    spread_high_low FLOAT,  -- FLOAT column for spread between high and low prices
    spread_close_open FLOAT, -- FLOAT column for spread between close and open prices
    security_id STRING(25), -- STRING column for security ID with a maximum length of 25 characters
    security_code INT       -- INTEGER column for security code
);

create table staging.industry
(
    ind_code varchar
    ,sect_code varchar
    ,industry varchar
    
);


create table staging.sector
(
    sect_code varchar
    ,mei_code varchar
    ,sector varchar
);
