use financial_analytics
create table dbo.macroeconomic_indicator
(
	 mei_code varchar(4) primary key
	,macro_economic_indicator varchar(50)
);

create table dbo.sector
(
	 sect_code varchar(6) primary key
	,mei_code varchar(4)
	,sector varchar(100)
	,foreign key (mei_code) references dbo.macroeconomic_indicator(mei_code)
	on delete cascade
	on update cascade
);

create table dbo.industry
(
	 ind_code varchar(8) primary key
	,sect_code varchar(6)
	,industry varchar(100)
	,foreign key(sect_code) references dbo.sector(sect_code)
	on delete cascade
	on update cascade
);


create table dbo.basic_industry
(
	 basic_ind_code varchar(11) primary key
	,ind_code varchar(8)
	,basic_industry varchar(max)
	,basic_industry_definition varchar(max)
	,basic_industry_search_optimized varchar(255)
	,foreign key(ind_code) references dbo.industry(ind_code)
	on delete cascade
	on update cascade
);


create table dbo.securities 
(
    [security_code] int,
    [issuer_name] varchar(250),
    [security_id] varchar(25),
    [security_name] varchar(250),
    [status] varchar(25),
    [group] varchar(max),
    [face_value] varchar(max),
    [isin_no] varchar(max),
    [instrument] varchar(max),
    [isubgroup_name] varchar(max),
	isubgroup_name_search_optimized varchar(255),
	primary key (security_code,security_id)
	
    
);

drop table if exists staging.stock_price_history ;
create table staging.stock_price_history
(
	
    [date] varchar(max),							-- date
    open_price varchar(max),                       -- open price of the fund
    high_price varchar(max),                       -- highest price during the day
    low_price varchar(max),                        -- lowest price during the day
    close_price varchar(max),                      -- closing price of the fund
    wap varchar(max),                              -- weighted average price
    no_of_shares varchar(max),                       -- number of shares traded
    no_of_trades varchar(max),                       -- number of trades executed
    total_turnover_rs varchar(max),                -- total turnover in rupees
    deliverable_quantity varchar(max),               -- quantity of shares delivered
    percent_deli_qty_to_traded_qty varchar(max),   -- percentage of deliverable quantity to traded quantity
    spread_high_low varchar(max),                  -- difference between high and low prices
    spread_close_open varchar(max),                -- difference between closing and opening prices
	security_id varchar(max),					-- unique ticker symbol for stock
	security_code varchar(max)							-- unique security id for stock from the bse database
);


drop table if exists dbo.stock_price_history ;
create table dbo.stock_price_history 
(
	id int identity(1,1) primary key ,
    [date] date,							-- date
    open_price float,                       -- open price of the fund
    high_price float,                       -- highest price during the day
    low_price float,                        -- lowest price during the day
    close_price float,                      -- closing price of the fund
    wap float,                              -- weighted average price
    no_of_shares int,                       -- number of shares traded
    no_of_trades int,                       -- number of trades executed
    total_turnover_rs float,                -- total turnover in rupees
    deliverable_quantity int,               -- quantity of shares delivered
    percent_deli_qty_to_traded_qty float,   -- percentage of deliverable quantity to traded quantity
    spread_high_low float,                  -- difference between high and low prices
    spread_close_open float,                -- difference between closing and opening prices
	security_id varchar(25),					-- unique ticker symbol for stock
	security_code int							-- unique security id for stock from the bse database
	,foreign key (security_code,security_id) references dbo.securities(security_code,security_id)
);

drop table if exists financial_analytics.staging.balance_sheet ;
create table financial_analytics.staging.balance_sheet (
    date varchar(max),
    treasury_shares_number varchar(max),
    ordinary_shares_number varchar(max),
    share_issued varchar(max),
    total_debt varchar(max),
    tangible_book_value varchar(max),
    invested_capital varchar(max),
    working_capital varchar(max),
    net_tangible_assets varchar(max),
    capital_lease_obligations varchar(max),
    common_stock_equity varchar(max),
    total_capitalization varchar(max),
    total_equity_gross_minority_interest varchar(max),
    stockholders_equity varchar(max),
    other_equity_interest varchar(max),
    retained_earnings varchar(max),
    additional_paid_in_capital varchar(max),
    capital_stock varchar(max),
    common_stock varchar(max),
    total_liabilities_net_minority_interest varchar(max),
    total_non_current_liabilities_net_minority_interest varchar(max),
    derivative_product_liabilities varchar(max),
    long_term_debt_and_capital_lease_obligation varchar(max),
    long_term_capital_lease_obligation varchar(max),
    long_term_debt varchar(max),
    long_term_provisions varchar(max),
    current_liabilities varchar(max),
    other_current_liabilities varchar(max),
    current_deferred_taxes_liabilities varchar(max),
    current_debt_and_capital_lease_obligation varchar(max),
    current_capital_lease_obligation varchar(max),
    pensionand_other_post_retirement_benefit_plans_current varchar(max),
    current_provisions varchar(max),
    payables varchar(max),
    other_payable varchar(max),
    dividends_payable varchar(max),
    total_tax_payable varchar(max),
    accounts_payable varchar(max),
    total_assets varchar(max),
    total_non_current_assets varchar(max),
    other_non_current_assets varchar(max),
    non_current_prepaid_assets varchar(max),
    non_current_deferred_taxes_assets varchar(max),
    financial_assets varchar(max),
    other_investments varchar(max),
    investmentin_financial_assets varchar(max),
    held_to_maturity_securities varchar(max),
    available_for_sale_securities varchar(max),
    goodwill_and_other_intangible_assets varchar(max),
    other_intangible_assets varchar(max),
    goodwill varchar(max),
    net_ppe varchar(max),
    accumulated_depreciation varchar(max),
    gross_ppe varchar(max),
    construction_in_progress varchar(max),
    other_properties varchar(max),
    machinery_furniture_equipment varchar(max),
    buildings_and_improvements varchar(max),
    land_and_improvements varchar(max),
    properties varchar(max),
    current_assets varchar(max),
    other_current_assets varchar(max),
    hedging_assets_current varchar(max),
    assets_held_for_sale_current varchar(max),
    restricted_cash varchar(max),
    prepaid_assets varchar(max),
    inventory varchar(max),
    finished_goods varchar(max),
    work_in_process varchar(max),
    raw_materials varchar(max),
    other_receivables varchar(max),
    taxes_receivable varchar(max),
    accounts_receivable varchar(max),
    allowance_for_doubtful_accounts_receivable varchar(max),
    gross_accounts_receivable varchar(max),
    cash_cash_equivalents_and_short_term_investments varchar(max),
    other_short_term_investments varchar(max),
    cash_and_cash_equivalents varchar(max),
    cash_equivalents varchar(max),
    cash_financial varchar(max),
    security_code varchar(max),
    security_id varchar(max),
    net_debt varchar(max),
    minority_interest varchar(max),
    other_non_current_liabilities varchar(max),
    non_current_pension_and_other_postretirement_benefit_plans varchar(max),
    non_current_deferred_revenue varchar(max),
    non_current_deferred_taxes_liabilities varchar(max),
    current_debt varchar(max),
    other_inventories varchar(max),
    financial_assets_designatedas_fair_value_through_profitor_loss_total varchar(max),
    trading_securities varchar(max),
    long_term_equity_investment varchar(max),
    investmentsin_joint_venturesat_cost varchar(max),
    investmentsin_associatesat_cost varchar(max),
    preferred_securities_outside_stock_equity varchar(max),
    tradeand_other_payables_non_current varchar(max),
    investments_in_other_ventures_under_equity_method varchar(max),
    investment_properties varchar(max),
    fixed_assets_revaluation_reserve varchar(max),
    preferred_stock varchar(max),
    defined_pension_benefit varchar(max),
    non_current_accrued_expenses varchar(max),
    investments_and_advances varchar(max),
    receivables varchar(max),
    cash_cash_equivalents_and_federal_funds_sold varchar(max),
    treasury_stock varchar(max),
    inventories_adjustments_allowances varchar(max),
    non_current_deferred_assets varchar(max),
    investmentsin_subsidiariesat_cost varchar(max),
    current_deferred_assets varchar(max),
    preferred_shares_number varchar(max),
    gains_losses_not_affecting_retained_earnings varchar(max),
    other_equity_adjustments varchar(max),
    non_current_deferred_liabilities varchar(max),
    current_deferred_liabilities varchar(max),
    current_deferred_revenue varchar(max),
    other_current_borrowings varchar(max),
    line_of_credit varchar(max),
    payables_and_accrued_expenses varchar(max),
    current_accrued_expenses varchar(max),
    non_current_accounts_receivable varchar(max),
    current_deferred_taxes_assets varchar(max),
    liabilities_heldfor_sale_non_current varchar(max),
    current_notes_payable varchar(max),
    employee_benefits varchar(max),
    income_tax_payable varchar(max),
    non_current_note_receivables varchar(max),
    accrued_interest_receivable varchar(max),
    loans_receivable varchar(max),
    preferred_stock_equity varchar(max),
    receivables_adjustments_allowances varchar(max),
    dueto_related_parties_non_current varchar(max),
    dueto_related_parties_current varchar(max),
    duefrom_related_parties_non_current varchar(max),
    duefrom_related_parties_current varchar(max),
    commercial_paper varchar(max),
    interest_payable varchar(max),
    notes_receivable varchar(max)
);


drop table if exists dbo.balance_sheet ;
create table dbo.balance_sheet (
	id int identity(1,1) primary key ,
    date date,
    treasury_shares_number decimal(18, 2),
    ordinary_shares_number decimal(18, 2),
    share_issued decimal(18, 2),
    total_debt decimal(18, 2),
    tangible_book_value decimal(18, 2),
    invested_capital decimal(18, 2),
    working_capital decimal(18, 2),
    net_tangible_assets decimal(18, 2),
    capital_lease_obligations decimal(18, 2),
    common_stock_equity decimal(18, 2),
    total_capitalization decimal(18, 2),
    total_equity_gross_minority_interest decimal(18, 2),
    stockholders_equity decimal(18, 2),
    other_equity_interest decimal(18, 2),
    retained_earnings decimal(18, 2),
    additional_paid_in_capital decimal(18, 2),
    capital_stock decimal(18, 2),
    common_stock decimal(18, 2),
    total_liabilities_net_minority_interest decimal(18, 2),
    total_non_current_liabilities_net_minority_interest decimal(18, 2),
    derivative_product_liabilities decimal(18, 2),
    long_term_debt_and_capital_lease_obligation decimal(18, 2),
    long_term_capital_lease_obligation decimal(18, 2),
    long_term_debt decimal(18, 2),
    long_term_provisions decimal(18, 2),
    current_liabilities decimal(18, 2),
    other_current_liabilities decimal(18, 2),
    current_deferred_taxes_liabilities decimal(18, 2),
    current_debt_and_capital_lease_obligation decimal(18, 2),
    current_capital_lease_obligation decimal(18, 2),
    pensionand_other_post_retirement_benefit_plans_current decimal(18, 2),
    current_provisions decimal(18, 2),
    payables decimal(18, 2),
    other_payable decimal(18, 2),
    dividends_payable decimal(18, 2),
    total_tax_payable decimal(18, 2),
    accounts_payable decimal(18, 2),
    total_assets decimal(18, 2),
    total_non_current_assets decimal(18, 2),
    other_non_current_assets decimal(18, 2),
    non_current_prepaid_assets decimal(18, 2),
    non_current_deferred_taxes_assets decimal(18, 2),
    financial_assets decimal(18, 2),
    other_investments decimal(18, 2),
    investmentin_financial_assets decimal(18, 2),
    held_to_maturity_securities decimal(18, 2),
    available_for_sale_securities decimal(18, 2),
    goodwill_and_other_intangible_assets decimal(18, 2),
    other_intangible_assets decimal(18, 2),
    goodwill decimal(18, 2),
    net_ppe decimal(18, 2),
    accumulated_depreciation decimal(18, 2),
    gross_ppe decimal(18, 2),
    construction_in_progress decimal(18, 2),
    other_properties decimal(18, 2),
    machinery_furniture_equipment decimal(18, 2),
    buildings_and_improvements decimal(18, 2),
    land_and_improvements decimal(18, 2),
    properties decimal(18, 2),
    current_assets decimal(18, 2),
    other_current_assets decimal(18, 2),
    hedging_assets_current decimal(18, 2),
    assets_held_for_sale_current decimal(18, 2),
    restricted_cash decimal(18, 2),
    prepaid_assets decimal(18, 2),
    inventory decimal(18, 2),
    finished_goods decimal(18, 2),
    work_in_process decimal(18, 2),
    raw_materials decimal(18, 2),
    other_receivables decimal(18, 2),
    taxes_receivable decimal(18, 2),
    accounts_receivable decimal(18, 2),
    allowance_for_doubtful_accounts_receivable decimal(18, 2),
    gross_accounts_receivable decimal(18, 2),
    cash_cash_equivalents_and_short_term_investments decimal(18, 2),
    other_short_term_investments decimal(18, 2),
    cash_and_cash_equivalents decimal(18, 2),
    cash_equivalents decimal(18, 2),
    cash_financial decimal(18, 2),
    net_debt decimal(18, 2),
    minority_interest decimal(18, 2),
    other_non_current_liabilities decimal(18, 2),
    non_current_pension_and_other_postretirement_benefit_plans decimal(18, 2),
    non_current_deferred_revenue decimal(18, 2),
    non_current_deferred_taxes_liabilities decimal(18, 2),
    current_debt decimal(18, 2),
    other_inventories decimal(18, 2),
    financial_assets_designatedas_fair_value_through_profitor_loss_total decimal(18, 2),
    trading_securities decimal(18, 2),
    long_term_equity_investment decimal(18, 2),
    investmentsin_joint_venturesat_cost decimal(18, 2),
    investmentsin_associatesat_cost decimal(18, 2),
    preferred_securities_outside_stock_equity decimal(18, 2),
    tradeand_other_payables_non_current decimal(18, 2),
    investments_in_other_ventures_under_equity_method decimal(18, 2),
    investment_properties decimal(18, 2),
    fixed_assets_revaluation_reserve decimal(18, 2),
    preferred_stock decimal(18, 2),
    defined_pension_benefit decimal(18, 2),
    non_current_accrued_expenses decimal(18, 2),
    investments_and_advances decimal(18, 2),
    receivables decimal(18, 2),
    cash_cash_equivalents_and_federal_funds_sold decimal(18, 2),
    treasury_stock decimal(18, 2),
    inventories_adjustments_allowances decimal(18, 2),
    non_current_deferred_assets decimal(18, 2),
    investmentsin_subsidiariesat_cost decimal(18, 2),
    current_deferred_assets decimal(18, 2),
    preferred_shares_number decimal(18, 2),
    gains_losses_not_affecting_retained_earnings decimal(18, 2),
    other_equity_adjustments decimal(18, 2),
    non_current_deferred_liabilities decimal(18, 2),
    current_deferred_liabilities decimal(18, 2),
    current_deferred_revenue decimal(18, 2),
    other_current_borrowings decimal(18, 2),
    line_of_credit decimal(18, 2),
    payables_and_accrued_expenses decimal(18, 2),
    current_accrued_expenses decimal(18, 2),
    non_current_accounts_receivable decimal(18, 2),
    current_deferred_taxes_assets decimal(18, 2),
    liabilities_heldfor_sale_non_current decimal(18, 2),
    current_notes_payable decimal(18, 2),
    employee_benefits decimal(18, 2),
    income_tax_payable decimal(18, 2),
    non_current_note_receivables decimal(18, 2),
    accrued_interest_receivable decimal(18, 2),
    loans_receivable decimal(18, 2),
    preferred_stock_equity decimal(18, 2),
    receivables_adjustments_allowances decimal(18, 2),
    dueto_related_parties_non_current decimal(18, 2),
    dueto_related_parties_current decimal(18, 2),
    duefrom_related_parties_non_current decimal(18, 2),
    duefrom_related_parties_current decimal(18, 2),
    commercial_paper decimal(18, 2),
    interest_payable decimal(18, 2),
    notes_receivable decimal(18, 2),
	security_id  varchar(25),
	security_code int
	,foreign key (security_code,security_id) references dbo.securities(security_code,security_id)
);


drop table if exists staging.income_statement
create table financial_analytics.staging.income_statement (
    date varchar(max),
    tax_effect_of_unusual_items varchar(max),
    tax_rate_for_calcs varchar(max),
    normalized_ebitda varchar(max),
    total_unusual_items varchar(max),
    total_unusual_items_excluding_goodwill varchar(max),
    net_income_from_continuing_operation_net_minority_interest varchar(max),
    reconciled_depreciation varchar(max),
    reconciled_cost_of_revenue varchar(max),
    ebitda varchar(max),
    ebit varchar(max),
    net_interest_income varchar(max),
    interest_expense varchar(max),
    interest_income varchar(max),
    normalized_income varchar(max),
    net_income_from_continuing_and_discontinued_operation varchar(max),
    total_expenses varchar(max),
    rent_expense_supplemental varchar(max),
    diluted_average_shares varchar(max),
    basic_average_shares varchar(max),
    diluted_eps varchar(max),
    basic_eps varchar(max),
    diluted_ni_availto_com_stockholders varchar(max),
    net_income_common_stockholders varchar(max),
    otherunder_preferred_stock_dividend varchar(max),
    net_income varchar(max),
    net_income_including_noncontrolling_interests varchar(max),
    net_income_discontinuous_operations varchar(max),
    net_income_continuous_operations varchar(max),
    tax_provision varchar(max),
    pretax_income varchar(max),
    other_non_operating_income_expenses varchar(max),
    special_income_charges varchar(max),
    other_special_charges varchar(max),
    write_off varchar(max),
    net_non_operating_interest_income_expense varchar(max),
    total_other_finance_cost varchar(max),
    interest_expense_non_operating varchar(max),
    interest_income_non_operating varchar(max),
    operating_income varchar(max),
    operating_expense varchar(max),
    other_operating_expenses varchar(max),
    depreciation_and_amortization_in_income_statement varchar(max),
    amortization varchar(max),
    depreciation_income_statement varchar(max),
    selling_general_and_administration varchar(max),
    selling_and_marketing_expense varchar(max),
    general_and_administrative_expense varchar(max),
    rent_and_landing_fees varchar(max),
    gross_profit varchar(max),
    cost_of_revenue varchar(max),
    total_revenue varchar(max),
    operating_revenue varchar(max),
    security_code varchar(max),
    security_id varchar(max),
    minority_interests varchar(max),
    research_and_development varchar(max),
    impairment_of_capital_assets varchar(max),
    gain_on_sale_of_security varchar(max),
    insurance_and_claims varchar(max),
    restructuring_and_mergern_acquisition varchar(max),
    net_income_extraordinary varchar(max),
    total_operating_income_as_reported varchar(max),
    other_income_expense varchar(max),
    gain_on_sale_of_ppe varchar(max),
    earnings_from_equity_interest varchar(max),
    average_dilution_earnings varchar(max),
    preferred_stock_dividends varchar(max),
    depreciation_amortization_depletion_income_statement varchar(max),
    amortization_of_intangibles_income_statement varchar(max),
    other_gand_a varchar(max),
    salaries_and_wages varchar(max),
    occupancy_and_equipment varchar(max),
    other_non_interest_expense varchar(max),
    gain_on_sale_of_business varchar(max),
    other_taxes varchar(max),
    net_policyholder_benefits_and_claims varchar(max),
    earnings_from_equity_interest_net_of_tax varchar(max),
    provision_for_doubtful_accounts varchar(max),
    professional_expense_and_contract_services_expense varchar(max)
);




drop table if exists dbo.income_statement;
create table dbo.income_statement (
	id int identity(1,1) primary key ,
    date nvarchar(50),
    tax_effect_of_unusual_items float,
    tax_rate_for_calcs float,
    normalized_ebitda float,
    total_unusual_items float,
    total_unusual_items_excluding_goodwill float,
    net_income_from_continuing_operation_net_minority_interest float,
    reconciled_depreciation float,
    reconciled_cost_of_revenue float,
    ebitda float,
    ebit float,
    net_interest_income float,
    interest_expense float,
    interest_income float,
    normalized_income float,
    net_income_from_continuing_and_discontinued_operation float,
    total_expenses float,
    rent_expense_supplemental float,
    diluted_average_shares float,
    basic_average_shares float,
    diluted_eps float,
    basic_eps float,
    diluted_ni_availto_com_stockholders float,
    net_income_common_stockholders float,
    otherunder_preferred_stock_dividend float,
    net_income float,
    net_income_including_noncontrolling_interests float,
    net_income_discontinuous_operations float,
    net_income_continuous_operations float,
    tax_provision float,
    pretax_income float,
    other_non_operating_income_expenses float,
    special_income_charges float,
    other_special_charges float,
    write_off float,
    net_non_operating_interest_income_expense float,
    total_other_finance_cost float,
    interest_expense_non_operating float,
    interest_income_non_operating float,
    operating_income float,
    operating_expense float,
    other_operating_expenses float,
    depreciation_and_amortization_in_income_statement float,
    amortization float,
    depreciation_income_statement float,
    selling_general_and_administration float,
    selling_and_marketing_expense float,
    general_and_administrative_expense float,
    rent_and_landing_fees float,
    gross_profit float,
    cost_of_revenue float,
    total_revenue float,
    operating_revenue float,
    minority_interests float,
    research_and_development float,
    impairment_of_capital_assets float,
    gain_on_sale_of_security float,
    insurance_and_claims float,
    restructuring_and_mergern_acquisition float,
    net_income_extraordinary float,
    total_operating_income_as_reported float,
    other_income_expense float,
    gain_on_sale_of_ppe float,
    earnings_from_equity_interest float,
    average_dilution_earnings float,
    preferred_stock_dividends float,
    depreciation_amortization_depletion_income_statement float,
    amortization_of_intangibles_income_statement float,
    other_gand_a float,
    salaries_and_wages float,
    occupancy_and_equipment float,
    other_non_interest_expense float,
    gain_on_sale_of_business float,
    other_taxes float,
    net_policyholder_benefits_and_claims float,
    earnings_from_equity_interest_net_of_tax float,
    provision_for_doubtful_accounts float,
    professional_expense_and_contract_services_expense float,
	security_id  varchar(25),
	security_code int
	,foreign key (security_code,security_id) references dbo.securities(security_code,security_id)
);


drop table if exists dbo.cash_flow;
create table dbo.cash_flow (
	id int identity(1,1) primary key ,
    date date,
    free_cash_flow decimal(18, 2),
    repayment_of_debt decimal(18, 2),
    capital_expenditure decimal(18, 2),
    end_cash_position decimal(18, 2),
    other_cash_adjustment_outside_changein_cash nvarchar(255),
    beginning_cash_position decimal(18, 2),
    effect_of_exchange_rate_changes decimal(18, 2),
    changes_in_cash decimal(18, 2),
    financing_cash_flow decimal(18, 2),
    interest_paid_cff nvarchar(255),
    cash_dividends_paid nvarchar(255),
    common_stock_dividend_paid nvarchar(255),
    net_issuance_payments_of_debt decimal(18, 2),
    net_long_term_debt_issuance decimal(18, 2),
    long_term_debt_payments decimal(18, 2),
    investing_cash_flow decimal(18, 2),
    net_other_investing_changes decimal(18, 2),
    interest_received_cfi decimal(18, 2),
    net_investment_purchase_and_sale decimal(18, 2),
    sale_of_investment decimal(18, 2),
    purchase_of_investment decimal(18, 2),
    net_business_purchase_and_sale decimal(18, 2),
    sale_of_business decimal(18, 2),
    purchase_of_business decimal(18, 2),
    net_ppe_purchase_and_sale decimal(18, 2),
    sale_of_ppe decimal(18, 2),
    purchase_of_ppe decimal(18, 2),
    operating_cash_flow decimal(18, 2),
    taxes_refund_paid nvarchar(255),
    change_in_working_capital decimal(18, 2),
    change_in_other_current_liabilities decimal(18, 2),
    change_in_other_current_assets decimal(18, 2),
    change_in_payable decimal(18, 2),
    change_in_inventory decimal(18, 2),
    change_in_receivables decimal(18, 2),
    other_non_cash_items decimal(18, 2),
    provisionand_write_offof_assets decimal(18, 2),
    depreciation_and_amortization decimal(18, 2),
    amortization_cash_flow decimal(18, 2),
    depreciation decimal(18, 2),
    gain_loss_on_investment_securities decimal(18, 2),
    net_foreign_currency_exchange_gain_loss decimal(18, 2),
    gain_loss_on_sale_of_ppe decimal(18, 2),
    gain_loss_on_sale_of_business decimal(18, 2),
    net_income_from_continuing_operations decimal(18, 2),
    issuance_of_debt decimal(18, 2),
    issuance_of_capital_stock decimal(18, 2),
    net_other_financing_charges decimal(18, 2),
    net_common_stock_issuance decimal(18, 2),
    common_stock_issuance decimal(18, 2),
    net_short_term_debt_issuance decimal(18, 2),
    short_term_debt_issuance decimal(18, 2),
    long_term_debt_issuance decimal(18, 2),
    dividends_received_cfi nvarchar(255),
    stock_based_compensation decimal(18, 2),
    pension_and_employee_benefit_expense decimal(18, 2),
    capital_expenditure_reported decimal(18, 2),
    short_term_debt_payments decimal(18, 2),
    net_investment_properties_purchase_and_sale decimal(18, 2),
    net_intangibles_purchase_and_sale decimal(18, 2),
    purchase_of_intangibles decimal(18, 2),
    other_cash_adjustment_inside_changein_cash nvarchar(255),
    repurchase_of_capital_stock decimal(18, 2),
    net_preferred_stock_issuance decimal(18, 2),
    preferred_stock_payments decimal(18, 2),
    common_stock_payments decimal(18, 2),
    sale_of_investment_properties decimal(18, 2),
    interest_received_cfo decimal(18, 2),
    interest_paid_cfo nvarchar(255),
    purchase_of_investment_properties decimal(18, 2),
    sale_of_intangibles decimal(18, 2),
    deferred_tax decimal(18, 2),
    dividend_received_cfo nvarchar(255),
    cash_flow_from_continuing_financing_activities decimal(18, 2),
    cash_flow_from_continuing_investing_activities decimal(18, 2),
    cash_flow_from_continuing_operating_activities decimal(18, 2),
    change_in_other_working_capital decimal(18, 2),
    change_in_payables_and_accrued_expense decimal(18, 2),
    unrealized_gain_loss_on_investment_securities decimal(18, 2),
    asset_impairment_charge decimal(18, 2),
    deferred_income_tax decimal(18, 2),
    depreciation_amortization_depletion decimal(18, 2),
    amortization_of_intangibles decimal(18, 2),
    operating_gains_losses decimal(18, 2),
    earnings_losses_from_equity_investments decimal(18, 2),
    change_in_prepaid_assets nvarchar(255),
    interest_paid_supplemental_data nvarchar(255),
    income_tax_paid_supplemental_data nvarchar(255),
    proceeds_from_stock_option_exercised decimal(18, 2),
    change_in_accrued_expense decimal(18, 2),
    change_in_account_payable decimal(18, 2),
    changes_in_account_receivables decimal(18, 2),
    preferred_stock_issuance decimal(18, 2),
    dividend_paid_cfo nvarchar(255),
    preferred_stock_dividend_paid nvarchar(255),
    cash_flowsfromusedin_operating_activities_direct decimal(18, 2),
    interest_paid_direct nvarchar(255),
    dividends_paid_direct nvarchar(255),
    classesof_cash_payments decimal(18, 2),
    other_cash_paymentsfrom_operating_activities decimal(18, 2),
    paymentson_behalfof_employees decimal(18, 2),
    paymentsto_suppliersfor_goodsand_services decimal(18, 2),
    classesof_cash_receiptsfrom_operating_activities decimal(18, 2),
    other_cash_receiptsfrom_operating_activities decimal(18, 2),
    receiptsfrom_customers decimal(18, 2),
    taxes_refund_paid_direct nvarchar(255),
    interest_received_direct decimal(18, 2),
    amortization_of_securities decimal(18, 2),
	security_id  varchar(25),
	security_code int
	,foreign key(security_code,security_id) references dbo.securities(security_code,security_id)
);


drop table if exists staging.cash_flow;
create table staging.cash_flow (
    date varchar(max),
    free_cash_flow varchar(max),
    repayment_of_debt varchar(max),
    capital_expenditure varchar(max),
    end_cash_position varchar(max),
    other_cash_adjustment_outside_changein_cash varchar(max),
    beginning_cash_position varchar(max),
    effect_of_exchange_rate_changes varchar(max),
    changes_in_cash varchar(max),
    financing_cash_flow varchar(max),
    interest_paid_cff varchar(max),
    cash_dividends_paid varchar(max),
    common_stock_dividend_paid varchar(max),
    net_issuance_payments_of_debt varchar(max),
    net_long_term_debt_issuance varchar(max),
    long_term_debt_payments varchar(max),
    investing_cash_flow varchar(max),
    net_other_investing_changes varchar(max),
    interest_received_cfi varchar(max),
    net_investment_purchase_and_sale varchar(max),
    sale_of_investment varchar(max),
    purchase_of_investment varchar(max),
    net_business_purchase_and_sale varchar(max),
    sale_of_business varchar(max),
    purchase_of_business varchar(max),
    net_ppe_purchase_and_sale varchar(max),
    sale_of_ppe varchar(max),
    purchase_of_ppe varchar(max),
    operating_cash_flow varchar(max),
    taxes_refund_paid varchar(max),
    change_in_working_capital varchar(max),
    change_in_other_current_liabilities varchar(max),
    change_in_other_current_assets varchar(max),
    change_in_payable varchar(max),
    change_in_inventory varchar(max),
    change_in_receivables varchar(max),
    other_non_cash_items varchar(max),
    provisionand_write_offof_assets varchar(max),
    depreciation_and_amortization varchar(max),
    amortization_cash_flow varchar(max),
    depreciation varchar(max),
    gain_loss_on_investment_securities varchar(max),
    net_foreign_currency_exchange_gain_loss varchar(max),
    gain_loss_on_sale_of_ppe varchar(max),
    gain_loss_on_sale_of_business varchar(max),
    net_income_from_continuing_operations varchar(max),
    security_code varchar(max),
    security_id varchar(max),
    issuance_of_debt varchar(max),
    issuance_of_capital_stock varchar(max),
    net_other_financing_charges varchar(max),
    net_common_stock_issuance varchar(max),
    common_stock_issuance varchar(max),
    net_short_term_debt_issuance varchar(max),
    short_term_debt_issuance varchar(max),
    long_term_debt_issuance varchar(max),
    dividends_received_cfi varchar(max),
    stock_based_compensation varchar(max),
    pension_and_employee_benefit_expense varchar(max),
    capital_expenditure_reported varchar(max),
    short_term_debt_payments varchar(max),
    net_investment_properties_purchase_and_sale varchar(max),
    net_intangibles_purchase_and_sale varchar(max),
    purchase_of_intangibles varchar(max),
    other_cash_adjustment_inside_changein_cash varchar(max),
    repurchase_of_capital_stock varchar(max),
    net_preferred_stock_issuance varchar(max),
    preferred_stock_payments varchar(max),
    common_stock_payments varchar(max),
    sale_of_investment_properties varchar(max),
    interest_received_cfo varchar(max),
    interest_paid_cfo varchar(max),
    purchase_of_investment_properties varchar(max),
    sale_of_intangibles varchar(max),
    deferred_tax varchar(max),
    dividend_received_cfo varchar(max),
    cash_flow_from_continuing_financing_activities varchar(max),
    cash_flow_from_continuing_investing_activities varchar(max),
    cash_flow_from_continuing_operating_activities varchar(max),
    change_in_other_working_capital varchar(max),
    change_in_payables_and_accrued_expense varchar(max),
    unrealized_gain_loss_on_investment_securities varchar(max),
    asset_impairment_charge varchar(max),
    deferred_income_tax varchar(max),
    depreciation_amortization_depletion varchar(max),
    amortization_of_intangibles varchar(max),
    operating_gains_losses varchar(max),
    earnings_losses_from_equity_investments varchar(max),
    change_in_prepaid_assets varchar(max),
    interest_paid_supplemental_data varchar(max),
    income_tax_paid_supplemental_data varchar(max),
    proceeds_from_stock_option_exercised varchar(max),
    change_in_accrued_expense varchar(max),
    change_in_account_payable varchar(max),
    changes_in_account_receivables varchar(max),
    preferred_stock_issuance varchar(max),
    dividend_paid_cfo varchar(max),
    preferred_stock_dividend_paid varchar(max),
    cash_flowsfromusedin_operating_activities_direct varchar(max),
    interest_paid_direct varchar(max),
    dividends_paid_direct varchar(max),
    classesof_cash_payments varchar(max),
    other_cash_paymentsfrom_operating_activities varchar(max),
    paymentson_behalfof_employees varchar(max),
    paymentsto_suppliersfor_goodsand_services varchar(max),
    classesof_cash_receiptsfrom_operating_activities varchar(max),
    other_cash_receiptsfrom_operating_activities varchar(max),
    receiptsfrom_customers varchar(max),
    taxes_refund_paid_direct varchar(max),
    interest_received_direct varchar(max),
    amortization_of_securities varchar(max)
);
