

create view staging.vw_cash_flow 
as
select
    cast(date as date) as report_date,
    cast(free_cash_flow as decimal(18, 2)) as free_cash_flow,
    cast(repayment_of_debt as decimal(18, 2)) as repayment_of_debt,
    cast(capital_expenditure as decimal(18, 2)) as capital_expenditure,
    cast(end_cash_position as decimal(18, 2)) as end_cash_position,
    cast(other_cash_adjustment_outside_changein_cash as nvarchar(255)) as other_cash_adjustment_outside,
    cast(beginning_cash_position as decimal(18, 2)) as beginning_cash_position,
    cast(effect_of_exchange_rate_changes as decimal(18, 2)) as exchange_rate_changes_effect,
    cast(changes_in_cash as decimal(18, 2)) as changes_in_cash,
    cast(financing_cash_flow as decimal(18, 2)) as financing_cash_flow,
    cast(interest_paid_cff as nvarchar(255)) as interest_paid_financing,
    cast(cash_dividends_paid as nvarchar(255)) as cash_dividends_paid,
    cast(common_stock_dividend_paid as nvarchar(255)) as common_stock_dividend_paid,
    cast(net_issuance_payments_of_debt as decimal(18, 2)) as net_debt_issuance_payments,
    cast(net_long_term_debt_issuance as decimal(18, 2)) as net_long_term_debt_issuance,
    cast(long_term_debt_payments as decimal(18, 2)) as long_term_debt_payments,
    cast(investing_cash_flow as decimal(18, 2)) as investing_cash_flow,
    cast(net_other_investing_changes as decimal(18, 2)) as net_other_investing_changes,
    cast(interest_received_cfi as decimal(18, 2)) as interest_received_investing,
    cast(net_investment_purchase_and_sale as decimal(18, 2)) as net_investment_purchase_sale,
    cast(sale_of_investment as decimal(18, 2)) as sale_of_investment,
    cast(purchase_of_investment as decimal(18, 2)) as purchase_of_investment,
    cast(net_business_purchase_and_sale as decimal(18, 2)) as net_business_purchase_sale,
    cast(sale_of_business as decimal(18, 2)) as sale_of_business,
    cast(purchase_of_business as decimal(18, 2)) as purchase_of_business,
    cast(net_ppe_purchase_and_sale as decimal(18, 2)) as net_ppe_purchase_sale,
    cast(sale_of_ppe as decimal(18, 2)) as sale_of_ppe,
    cast(purchase_of_ppe as decimal(18, 2)) as purchase_of_ppe,
    cast(operating_cash_flow as decimal(18, 2)) as operating_cash_flow,
    cast(taxes_refund_paid as nvarchar(255)) as taxes_refund_paid,
    cast(change_in_working_capital as decimal(18, 2)) as change_in_working_capital,
    cast(change_in_other_current_liabilities as decimal(18, 2)) as change_in_other_current_liabilities,
    cast(change_in_other_current_assets as decimal(18, 2)) as change_in_other_current_assets,
    cast(change_in_payable as decimal(18, 2)) as change_in_payable,
    cast(change_in_inventory as decimal(18, 2)) as change_in_inventory,
    cast(change_in_receivables as decimal(18, 2)) as change_in_receivables,
    cast(other_non_cash_items as decimal(18, 2)) as other_non_cash_items,
    cast(provisionand_write_offof_assets as decimal(18, 2)) as provision_write_off_assets,
    cast(depreciation_and_amortization as decimal(18, 2)) as depreciation_amortization,
    cast(amortization_cash_flow as decimal(18, 2)) as amortization_cash_flow,
    cast(depreciation as decimal(18, 2)) as depreciation,
    cast(gain_loss_on_investment_securities as decimal(18, 2)) as gain_loss_investment_securities,
    cast(net_foreign_currency_exchange_gain_loss as decimal(18, 2)) as net_foreign_currency_exchange_gain_loss,
    cast(gain_loss_on_sale_of_ppe as decimal(18, 2)) as gain_loss_sale_of_ppe,
    cast(gain_loss_on_sale_of_business as decimal(18, 2)) as gain_loss_sale_of_business,
    cast(net_income_from_continuing_operations as decimal(18, 2)) as net_income_continuing_operations,
    cast(issuance_of_debt as decimal(18, 2)) as issuance_of_debt,
    cast(issuance_of_capital_stock as decimal(18, 2)) as issuance_of_capital_stock,
    cast(net_other_financing_charges as decimal(18, 2)) as net_other_financing_charges,
    cast(net_common_stock_issuance as decimal(18, 2)) as net_common_stock_issuance,
    cast(common_stock_issuance as decimal(18, 2)) as common_stock_issuance,
    cast(net_short_term_debt_issuance as decimal(18, 2)) as net_short_term_debt_issuance,
    cast(short_term_debt_issuance as decimal(18, 2)) as short_term_debt_issuance,
    cast(long_term_debt_issuance as decimal(18, 2)) as long_term_debt_issuance,
    cast(dividends_received_cfi as nvarchar(255)) as dividends_received_investing,
    cast(stock_based_compensation as decimal(18, 2)) as stock_based_compensation,
    cast(pension_and_employee_benefit_expense as decimal(18, 2)) as pension_employee_benefit_expense,
    cast(capital_expenditure_reported as decimal(18, 2)) as capital_expenditure_reported,
    cast(short_term_debt_payments as decimal(18, 2)) as short_term_debt_payments,
    cast(net_investment_properties_purchase_and_sale as decimal(18, 2)) as net_investment_properties_purchase_sale,
    cast(net_intangibles_purchase_and_sale as decimal(18, 2)) as net_intangibles_purchase_sale,
    cast(purchase_of_intangibles as decimal(18, 2)) as purchase_of_intangibles,
    cast(other_cash_adjustment_inside_changein_cash as nvarchar(255)) as other_cash_adjustment_inside,
    cast(repurchase_of_capital_stock as decimal(18, 2)) as repurchase_of_capital_stock,
    cast(net_preferred_stock_issuance as decimal(18, 2)) as net_preferred_stock_issuance,
    cast(preferred_stock_payments as decimal(18, 2)) as preferred_stock_payments,
    cast(common_stock_payments as decimal(18, 2)) as common_stock_payments,
    cast(sale_of_investment_properties as decimal(18, 2)) as sale_of_investment_properties,
    cast(interest_received_cfo as decimal(18, 2)) as interest_received_operating,
    cast(interest_paid_cfo as nvarchar(255)) as interest_paid_operating,
    cast(purchase_of_investment_properties as decimal(18, 2)) as purchase_of_investment_properties,
    cast(sale_of_intangibles as decimal(18, 2)) as sale_of_intangibles,
    cast(deferred_tax as decimal(18, 2)) as deferred_tax,
    cast(dividend_received_cfo as nvarchar(255)) as dividend_received_operating,
    cast(cash_flow_from_continuing_financing_activities as decimal(18, 2)) as cash_flow_continuing_financing,
    cast(cash_flow_from_continuing_investing_activities as decimal(18, 2)) as cash_flow_continuing_investing,
    cast(cash_flow_from_continuing_operating_activities as decimal(18, 2)) as cash_flow_continuing_operating,
    cast(change_in_other_working_capital as decimal(18, 2)) as change_in_other_working_capital,
    cast(change_in_payables_and_accrued_expense as decimal(18, 2)) as change_in_payables_accrued_expense,
    cast(unrealized_gain_loss_on_investment_securities as decimal(18, 2)) as unrealized_gain_loss_investment_securities,
    cast(asset_impairment_charge as decimal(18, 2)) as asset_impairment_charge,
    cast(deferred_income_tax as decimal(18, 2)) as deferred_income_tax,
    cast(depreciation_amortization_depletion as decimal(18, 2)) as depreciation_amortization_depletion,
    cast(amortization_of_intangibles as decimal(18, 2)) as amortization_of_intangibles,
    cast(operating_gains_losses as decimal(18, 2)) as operating_gains_losses,
    cast(earnings_losses_from_equity_investments as decimal(18, 2)) as equity_investments_earnings_losses,
    cast(change_in_prepaid_assets as nvarchar(255)) as change_in_prepaid_assets,
    cast(interest_paid_supplemental_data as nvarchar(255)) as interest_paid_supplemental,
    cast(income_tax_paid_supplemental_data as nvarchar(255)) as income_tax_paid_supplemental,
    cast(proceeds_from_stock_option_exercised as decimal(18, 2)) as stock_option_proceeds_exercised,
    cast(change_in_accrued_expense as decimal(18, 2)) as change_in_accrued_expense,
    cast(change_in_account_payable as decimal(18, 2)) as change_in_account_payable,
    cast(changes_in_account_receivables as decimal(18, 2)) as changes_in_account_receivables,
    cast(preferred_stock_issuance as decimal(18, 2)) as preferred_stock_issuance,
    cast(dividend_paid_cfo as nvarchar(255)) as dividend_paid_operating,
    cast(preferred_stock_dividend_paid as nvarchar(255)) as preferred_stock_dividend_paid,
    cast(cash_flowsfromusedin_operating_activities_direct as decimal(18, 2)) as cash_flows_used_operating_direct,
    cast(interest_paid_direct as nvarchar(255)) as interest_paid_direct,
    cast(dividends_paid_direct as nvarchar(255)) as dividends_paid_direct,
    cast(classesof_cash_payments as decimal(18, 2)) as cash_payment_classes,
    cast(other_cash_paymentsfrom_operating_activities as decimal(18, 2)) as other_cash_operating_payments,
    cast(paymentson_behalfof_employees as decimal(18, 2)) as payments_on_behalf_employees,
    cast(paymentsto_suppliersfor_goodsand_services as decimal(18, 2)) as payments_to_suppliers,
    cast(classesof_cash_receiptsfrom_operating_activities as decimal(18, 2)) as cash_receipt_classes_operating,
    cast(other_cash_receiptsfrom_operating_activities as decimal(18, 2)) as other_cash_operating_receipts,
    cast(receiptsfrom_customers as decimal(18, 2)) as receipts_from_customers,
    cast(taxes_refund_paid_direct as nvarchar(255)) as taxes_refund_paid_direct,
    cast(interest_received_direct as decimal(18, 2)) as interest_received_direct,
    cast(amortization_of_securities as decimal(18, 2)) as securities_amortization,
    cast(replace(cf.security_id, '.BO', '') as varchar(25)) as security_id,
    cast(cast(cf.security_code as float) as int) as security_code
from financial_analytics.staging.cash_flow cf
inner join financial_analytics.dbo.securities s
    on s.security_code = cf.security_code
    and s.security_id = replace(cf.security_id, '.BO', '');